import os
import csv
import argparse
import subprocess
import shutil
from abc import ABC, abstractmethod

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

import torchvision.models as models
from transformers import AutoModel, AutoImageProcessor
from huggingface_hub import login
import timm


class BaseExtractor(ABC):
    def __init__(self, device, hf_token=None):
        self.device = device
        self.hf_token = hf_token

        if self.hf_token:
            print("Logging to Hugging Face...")
            login(token=self.hf_token)

        self.model = self._load_model()
        self.model.to(self.device)
        self.model.eval()

    @abstractmethod
    def _load_model(self) -> nn.Module:
        """Method responsible for loading a concrete model."""
        pass

    @abstractmethod
    def extract(self, images: torch.Tensor) -> torch.Tensor:
        """Method for extracting features from a batch."""
        pass

    def get_transform(self):
        """Default transformation (ImageNet) for CTransPath, ResNet and UNI"""
        return transforms.Compose([
            transforms.Resize(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
        ])


class CTransPathExtractor(BaseExtractor):
    def __init__(self, device, weights_path, hf_token=None):
        self.weights_path = weights_path
        super().__init__(device, hf_token)

    def _load_model(self):
        print("Loading model CTransPath...")
        from TransPath.ctran import ctranspath
        model = ctranspath()
        model.head = nn.Identity()
        td = torch.load(self.weights_path, map_location=self.device)
        model.load_state_dict(td['model'], strict=True)
        return model

    def extract(self, images):
        return self.model(images)


class ResNet50Extractor(BaseExtractor):
    def _load_model(self):
        print("Loading model ResNet50...")
        model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
        model.fc = nn.Identity()
        return model

    def extract(self, images):
        return self.model(images)


class PhikonExtractor(BaseExtractor):
    def _load_model(self):
        print("Loading model Phikon (Owkin)...")
        self.processor = AutoImageProcessor.from_pretrained("owkin/phikon-v2")
        return AutoModel.from_pretrained("owkin/phikon-v2")

    def get_transform(self):
        # Overriding transformation and using official HuggingFace processor
        def transform_fn(image):
            # Returning 'pixel_values' tensor generated by the processor
            return self.processor(image, return_tensors="pt")['pixel_values'].squeeze(0)

        return transform_fn

    def extract(self, images):
        # Phikon from HuggingFace returns a dictionary, returning a CLS token
        outputs = self.model(pixel_values=images)
        return outputs.last_hidden_state[:, 0, :]


class UniExtractor(BaseExtractor):
    def _load_model(self):
        print("Loading model UNI (Mahmood Lab)...")
        return timm.create_model("hf_hub:MahmoodLab/uni", pretrained=True, init_values=1e-5, dynamic_img_size=True)

    def extract(self, images):
        return self.model(images)


class ExtractorFactory:
    @staticmethod
    def create(model_name: str, device: torch.device, weights_path: str = None, hf_token: str = None) -> BaseExtractor:
        name = model_name.lower()
        if name == 'ctranspath':
            if not weights_path:
                raise ValueError("CTransPath expects a path to its weights!")
            return CTransPathExtractor(device, weights_path, hf_token)
        elif name == 'resnet50':
            return ResNet50Extractor(device, hf_token)
        elif name == 'phikon':
            return PhikonExtractor(device, hf_token)
        elif name == 'uni':
            return UniExtractor(device, hf_token)
        else:
            raise ValueError(f"Unknown feature extractor: {model_name}")


class WSIPatchDataset(Dataset):
    def __init__(self, csv_file, patch_dir, transform):
        self.patch_dir = patch_dir
        self.patches = []
        self.transform = transform
        with open(csv_file, 'r') as f:
            reader = csv.reader(f)
            next(reader)
            for row in reader:
                self.patches.append(row[0])

    def __len__(self):
        return len(self.patches)

    def __getitem__(self, idx):
        patch_name = self.patches[idx]
        img_path = os.path.join(self.patch_dir, patch_name)
        image = Image.open(img_path).convert('RGB')
        return self.transform(image), patch_name


def main():
    parser = argparse.ArgumentParser(description="Feature extraction manager")
    parser.add_argument('--model', type=str, required=True, choices=['resnet50', 'ctranspath', 'phikon', 'uni'],
                        help="Choose feature extractor (resnet50, ctranspath, phikon, uni)")
    parser.add_argument('--zip_path', type=str,
                        default="/lustre/pd03/hpc-ljelen-1692966897/WSI/WSI_patched_png/benignMGG.zip",
                        help="Path to .zip archive with patches")
    parser.add_argument('--csv_dir', type=str, default="/home/piomac5688/projekt_wsi/csv_filtered_patches/benignMGG",
                        help="Main folder including subfolders of patients with good_patches.csv")
    parser.add_argument('--output_dir', type=str, default="/home/piomac5688/projekt_wsi/extracted_features/benignMGG",
                        help="Target folder for .pt files")
    parser.add_argument('--weights', type=str, default="/home/piomac5688/projekt_wsi/ctranspath.pth",
                        help="Path to CTransPath weights")
    parser.add_argument('--hf_token', type=str, default=None,
                        help="Hugging Face User Access Token (needed for UNI and Phikon)")
    args = parser.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Used device: {device}")

    # final_output_dir = f"{args.output_dir}_{args.model}"
    final_output_dir = os.path.join(args.output_dir, args.model)
    os.makedirs(final_output_dir, exist_ok=True)
    TMPDIR = os.environ.get('TMPDIR', '/tmp')

    extractor = ExtractorFactory.create(args.model, device, args.weights, args.hf_token)
    model_transform = extractor.get_transform()

    slides = [d for d in os.listdir(args.csv_dir) if os.path.isdir(os.path.join(args.csv_dir, d))]
    print(f"Found {len(slides)} patients for feature extraction.")

    with torch.no_grad():
        for i, slide_name in enumerate(slides, 1):
            output_pt_file = os.path.join(final_output_dir, f"{slide_name}.pt")

            if os.path.exists(output_pt_file):
                print(f"[{i}/{len(slides)}] Skipping {slide_name} - features are already extracted.")
                continue

            subprocess.run(["unzip", "-q", args.zip_path, f"*{slide_name}/*", "-d", TMPDIR], check=False)

            csv_file = os.path.join(args.csv_dir, slide_name, "good_patches.csv")

            found_patch_dirs = [os.path.join(root, d) for root, dirs, _ in os.walk(TMPDIR) for d in dirs if
                                d == slide_name]
            if not found_patch_dirs:
                print(f"[{i}/{len(slides)}] Skipping {slide_name} - No files unpacked in TMPDIR!")
                continue

            patch_dir = found_patch_dirs[0]
            print(f"[{i}/{len(slides)}] Feature extractor ({args.model}) for: {slide_name}...")

            dataset = WSIPatchDataset(csv_file, patch_dir, transform=model_transform)
            dataloader = DataLoader(dataset, batch_size=256, shuffle=False, num_workers=2)

            slide_features = []

            for batch_idx, (images, _) in enumerate(dataloader):
                images = images.to(device)

                features = extractor.extract(images)

                slide_features.append(features.cpu())

            if len(slide_features) > 0:
                final_tensor = torch.cat(slide_features, dim=0)
                torch.save(final_tensor, output_pt_file)
                print(f"   -> Saved tensor {final_tensor.shape} to {slide_name}.pt")
            else:
                print(f"   -> Warning: Slide {slide_name} did not have any filtered patches.")

            shutil.rmtree(patch_dir, ignore_errors=True)


if __name__ == "__main__":
    main()